### ISSUE TITLE
Ofrecimiento de ayuda

### ISSUE THREAD

**Issue by PSF1** [jlrtutor/Spectrum-Codigo-Maquina-Microhobby#1]
Hola Juan,

En primer lugar, gracias por el tremendo esfuerzo de remaquetar este curso de MicroHobby.

Estoy haciendo un script que, a partir de las imagenes escaneados por Robert Perelegre, rota, corta y suma en un PDF todo el curso de código máquina. ¿Te ayudaría tener las imagenes ya rotadas y cortadas o incluso montadas en un PDF cuando lo tenga?

No es mi ntención frustrar tu proyecto, te dejo esta issue con la idea de ayudar.

Gracias

**Comment by PSF1** [comment]
Acabo de ver que vives en Sevilla :_ D Yo en Huelva, estamos muy cerca : ))

**Comment by jlrtutor** [comment]
Hola, Pedro

Muchísimas gracias por interesarte en el proyecto y por ofrecer ayuda (eres
el primero, jaja).

Lo que comentas es diferente a lo que estoy haciendo. Hice pruebas
recortando las figuras, gráficas o esquemas y reescalándolas mediante IA,
pero luego al visualizar el documento y hacer zoom, llega un punto que se
ven los píxeles.
Al imprimir el documento mejora la versión que hay por la red, pero no es
suficiente porque la versión digital en PDF se nota bastante.
Es por eso por lo que estoy pasando todos los gráficos a formato vectorial
(un trabajo, ya lo sé), para que tanto impreso como al hacer zoom, se vea
100% perfecto siempre.

Seguimos en contacto (por Twitter si quieres) y gracias de nuevo!

Juan Luis

**Comment by PSF1** [comment]
De nada, twitter lo uso poco (o nada :_ D ) Estoy normalmente en el telegram del Mundo del Spectrum y en el slack de Drupal (como PSF).

Gracias y estaré atento al progreso ;)
